export interface GeneratorMetadata {
    generator: string;
    generated_at: string;
    warning: string;
    target_path: string;
    format: string;
    [key: string]: any;
}

export function createMetadata(
    targetPath: string,
    format: string,
    extra?: Record<string, any>
): GeneratorMetadata {
    return {
        generator: "axogen",
        generated_at: new Date().toISOString(),
        warning: "This file was generated automatically - do not edit manually",
        target_path: targetPath,
        format,
        ...extra,
    };
}

export function createHeaderComments(
    targetPath: string,
    format?: string,
    prefix: string = "#",
    suffix: string = ""
): string[] {
    const comments = [
        `${prefix} Generated by axogen - do not edit manually ${suffix}`,
        `${prefix} Generated at ${new Date().toISOString()} ${suffix}`,
        `${prefix} Target: ${targetPath} ${suffix}`,
    ];

    if (format) {
        comments.push(`${prefix} Format: ${format} ${suffix}`);
    }

    return comments;
}
